-- MySQL Script generated by MySQL Workbench
-- 11/19/14 05:33:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ten_thousand_tournaments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ten_thousand_tournaments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ten_thousand_tournaments` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ten_thousand_tournaments` ;

-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`locations` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`users` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`positions` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`players` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`players` (
  `id` INT NOT NULL,
  `jersey_number` VARCHAR(3) NULL,
  `position` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_players_positions_idx` (`position` ASC),
  CONSTRAINT `fk_players_users`
    FOREIGN KEY (`id`)
    REFERENCES `ten_thousand_tournaments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_positions`
    FOREIGN KEY (`position`)
    REFERENCES `ten_thousand_tournaments`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`teams` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date_registered` DATETIME NULL,
  `rep_player_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_players_idx` (`rep_player_id` ASC),
  CONSTRAINT `fk_teams_players`
    FOREIGN KEY (`rep_player_id`)
    REFERENCES `ten_thousand_tournaments`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`divisions` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`divisions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `rank` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`game_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`game_states` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`game_states` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`games` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `home_team_id` INT NULL,
  `away_team_id` INT NULL,
  `date_time` DATETIME NOT NULL,
  `division_id` INT NOT NULL,
  `game_state_id` INT NULL,
  `home_score` INT NULL,
  `away_score` INT NULL,
  `location_id` INT NOT NULL,
  `season_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_games_locations_idx` (`location_id` ASC),
  INDEX `fk_games_teams_home_idx` (`home_team_id` ASC),
  INDEX `fk_games_teams_away_idx` (`away_team_id` ASC),
  INDEX `fk_games_divisions_idx` (`division_id` ASC),
  INDEX `fk_games_game_states_idx` (`game_state_id` ASC),
  CONSTRAINT `fk_games_locations`
    FOREIGN KEY (`location_id`)
    REFERENCES `ten_thousand_tournaments`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_teams_home`
    FOREIGN KEY (`home_team_id`)
    REFERENCES `ten_thousand_tournaments`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_teams_away`
    FOREIGN KEY (`away_team_id`)
    REFERENCES `ten_thousand_tournaments`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_divisions`
    FOREIGN KEY (`division_id`)
    REFERENCES `ten_thousand_tournaments`.`divisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_game_states`
    FOREIGN KEY (`game_state_id`)
    REFERENCES `ten_thousand_tournaments`.`game_states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`titles` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`groups` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_title_idx` (`title_id` ASC),
  CONSTRAINT `fk_groups_title`
    FOREIGN KEY (`title_id`)
    REFERENCES `ten_thousand_tournaments`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`sports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`sports` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`sports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`leagues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`leagues` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`leagues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `sport_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_leagues_sport_idx` (`sport_id` ASC),
  CONSTRAINT `fk_leagues_sport`
    FOREIGN KEY (`sport_id`)
    REFERENCES `ten_thousand_tournaments`.`sports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`seasons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`seasons` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`seasons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NULL,
  `league_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seasons_leagues1_idx` (`league_id` ASC),
  CONSTRAINT `fk_seasons_leagues1`
    FOREIGN KEY (`league_id`)
    REFERENCES `ten_thousand_tournaments`.`leagues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`divisions_players_seasons_teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`divisions_players_seasons_teams` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`divisions_players_seasons_teams` (
  `division_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `season_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  INDEX `fk_divisions_players_seasons_teams_teams_idx` (`team_id` ASC),
  INDEX `fk_divisions_players_seasons_teams_divisions_idx` (`division_id` ASC),
  INDEX `fk_divisions_players_seasons_teams_seasons_idx` (`season_id` ASC),
  INDEX `fk_divisions_players_seasons_teams_players_idx` (`player_id` ASC),
  CONSTRAINT `fk_divisions_players_seasons_teams_teams`
    FOREIGN KEY (`team_id`)
    REFERENCES `ten_thousand_tournaments`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_divisions_players_seasons_teams_divisions`
    FOREIGN KEY (`division_id`)
    REFERENCES `ten_thousand_tournaments`.`divisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_divisions_players_seasons_teams_season`
    FOREIGN KEY (`season_id`)
    REFERENCES `ten_thousand_tournaments`.`seasons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_divisions_players_seasons_teams_players`
    FOREIGN KEY (`player_id`)
    REFERENCES `ten_thousand_tournaments`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`admins` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrators_users`
    FOREIGN KEY (`id`)
    REFERENCES `ten_thousand_tournaments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`referees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`referees` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`referees` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_referees_users1`
    FOREIGN KEY (`id`)
    REFERENCES `ten_thousand_tournaments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`groups_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`groups_users` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`groups_users` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  INDEX `fk_groups_users_users_idx` (`user_id` ASC),
  INDEX `fk_groups_users_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_groups_users_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ten_thousand_tournaments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_users_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `ten_thousand_tournaments`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`roles` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roles_title_idx` (`title_id` ASC),
  CONSTRAINT `fk_roles_title`
    FOREIGN KEY (`title_id`)
    REFERENCES `ten_thousand_tournaments`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ten_thousand_tournaments`.`admins_leagues_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ten_thousand_tournaments`.`admins_leagues_roles` ;

CREATE TABLE IF NOT EXISTS `ten_thousand_tournaments`.`admins_leagues_roles` (
  `league_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `fk_admins_leagues_roles_leagues_idx` (`league_id` ASC),
  INDEX `fk_admins_leagues_roles_admins_idx` (`admin_id` ASC),
  INDEX `fk_admins_leagues_roles_roles_idx` (`role_id` ASC),
  CONSTRAINT `fk_admins_leagues_roles_leagues`
    FOREIGN KEY (`league_id`)
    REFERENCES `ten_thousand_tournaments`.`leagues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admins_leagues_roles_admins`
    FOREIGN KEY (`admin_id`)
    REFERENCES `ten_thousand_tournaments`.`admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admins_leagues_roles_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `ten_thousand_tournaments`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
